spring.datasource.url=jdbc:postgresql://mainline.proxy.rlwy.net:42906/railway
spring.datasource.username=postgres
spring.datasource.password=LtOUirzzKGNEjnplihccYJCoWwLElnOx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true




jwt.secret=SFMyNTYsaGxzYWs3NDhAMzIxNHNoZ2toZ2xoQHNoZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2po
jwt.expiration=86400000