# Local PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://45.119.82.37:5432/wear2ndchange
spring.datasource.username=user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=5000

# Code-first approach
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080

spring.web.resources.static-locations=file:/home/ubuntu/uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoang57cd3@gmail.com
spring.mail.password=cyzk nmbe zyew tijv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=SFMyNTYsaGxzYWs3NDhAMzIxNHNoZ2toZ2xoQHNoZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2poZ2tqa2po
jwt.expiration=86400000


# PayOS Configuration

payos.client-id= 8fb507ac-1692-441a-a898-5c873e1a71c3
payos.api-key= 89e03ecc-f7f2-4fcb-a1fa-61139efe94a3
payos.checksum-key= 797478e48005f8de2060a3f5d46b9901d3d3163028ce9bb0d88df792623cd889
payos.return-url=https://wear2ndchance.vercel.app/checkout
payos.cancel-url=https://wear2ndchance.vercel.app/api/payment/payos/cancel


